@api = http://localhost:8080/

###########

POST {{api}}api/usuarios
Content-Type: application/json

{
    "nombre": "Alonso2",
    "correo": "2@gmail",
    "password": "asdf123.",
    "google": true,
    "rol": "userRole"
}